Plat 647
juwai/ansible-role-python27 pull request #11
Opened 2017-11-14 05:36 UTC by zhangjustin

## Summary of changes

Change the download url.

## How to Test
```
- src: git@github.com:zhangjustin/ansible-role-python27.git
  scm: git
  name: juwai.python27
  version: 884287408a60f355cce3a16e9ddd42c7313c139d
```
I had test in centos-68(juwai-admin) and centos-65(juwai-com-v2), all works.

/fyi: @tjoelsson , @mark-juwai : Please review.

2017-11-14 05:36 UTC, zhangjustin commented
@tjoelsson , It works, but need to remove `--version`.

2017-11-14 06:11 UTC, tjoelsson commented
If get-pip script installs pip, you can remove the other task for installing pip

2017-11-14 06:30 UTC, tjoelsson requested changes

2017-11-14 06:30 UTC, tjoelsson commented on tasks/centos6.yml
>  - name: download setuptools
download pip install script

2017-11-14 06:30 UTC, tjoelsson commented on tasks/centos6.yml
>  - name: install setuptools
install pip, setuptools, and wheel

2017-11-14 06:30 UTC, tjoelsson commented on tasks/centos6.yml
>    when: easy_install_check|failed
or pip_check|failed

2017-11-14 07:39 UTC, zhangjustin commented
Updated, please review.

2017-11-14 07:43 UTC, tjoelsson commented on tasks/centos6.yml
> +  when: pip_check|failed
easy_install_check|failed or pip_check|failed

2017-11-14 08:14 UTC, tjoelsson approved these changes

2017-11-15 02:39 UTC, mark-juwai approved these changes

2017-11-15 03:03 UTC, merged